INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:23:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:23:41] "GET /static/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:23:41] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:25:26] "GET /?s=hgfvhj HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:25:26] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:25:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 11:25:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:00] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:04] "GET /search?s=jhbjh HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:04] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:22:21] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:25:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:25:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:26:00] "GET /search?s=jbj HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:26:00] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:26:07] "GET /search?s=Ага HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 12:26:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:04:40] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:04:40] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:01] "GET /search?s=ага HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:01] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:03] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:11] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:11] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:19] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:19] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'loader_blueprint.create_new_post_by_user' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
ERROR:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] code 400, message Bad request syntax ('------WebKitFormBoundarysioMDVriVbvNCwuX')
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mNone /post HTTP/0.9[0m" HTTPStatus.BAD_REQUEST -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'loader_blueprint.create_new_post_by_user' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
ERROR:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] code 400, message Bad request syntax ('------WebKitFormBoundarysioMDVriVbvNCwuX')
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mNone /post HTTP/0.9[0m" HTTPStatus.BAD_REQUEST -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'loader_blueprint.create_new_post_by_user' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
ERROR:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] code 400, message Bad request syntax ('------WebKitFormBoundarysioMDVriVbvNCwuX')
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:40] "[35m[1mNone /post HTTP/0.9[0m" HTTPStatus.BAD_REQUEST -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:49] "GET /search?s=jhbjh HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:49] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:05:53] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:07] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Данные не загружены, отсутствует часть данных
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:13] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:15] "GET /post HTTP/1.1" 200 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'loader_blueprint.create_new_post_by_user' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:20] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:root:Данные не загружены, отсутствует часть данных
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:29] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:13:31] "GET /post HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 24, in create_new_post_by_user
    picture.save(UPLOAD_FOLDER)
  File "C:\Python395\lib\site-packages\werkzeug\datastructures.py", line 2996, in save
    dst = open(dst, "wb")
PermissionError: [Errno 13] Permission denied: 'uploads/images'
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:22:58] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:30:31] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:30:35] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:30:39] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:30:43] "GET /post HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:45:53] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:45:53] "GET /uploads/images/IMG_9285.JPG HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:45:53] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:03] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:06] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:06] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:20] "GET /search?s=новый HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:20] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:20] "[36mGET /uploads/images/IMG_9285.JPG HTTP/1.1[0m" 304 -
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:24] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:46:24] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:48:59] "GET /search?s= HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:48:59] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 13:48:59] "[36mGET /uploads/images/IMG_9285.JPG HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Выполняется поиск
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:15] "GET /search?s= HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:15] "[36mGET /uploads/images/IMG_9285.JPG HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:22] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:22] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 25, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!
INFO:werkzeug:127.0.0.1 - - [02/May/2022 14:15:44] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:00:02] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:00:07] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:00:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:00:16] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:02:03] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:06:13] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:06:13] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:06:14] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:06:14] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:06:26] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:07:27] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:07:50] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:Открытие главной страницы
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:13:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:13:03] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:13:07] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:13:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 28, in create_new_post_by_user
    new_post = {"pic": save_picture(picture), "content": content}
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\utils.py", line 17, in save_picture
    raise WrongImgType(f"Неверный формат файла! Допустим только {', '.join(allowed_type)}!")
exceptions.WrongImgType: Неверный формат файла! Допустим только jpg, png, gif, jpeg!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python395\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python395\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python395\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\SkyPro\lesson_12_copy_repozitory\loader\views.py", line 30, in create_new_post_by_user
    abort(400)
TypeError: nt.abort() takes no arguments (1 given)
INFO:werkzeug:127.0.0.1 - - [02/May/2022 15:13:16] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
